language: node_js
sudo: false
node_js:
  - "8"
  - "6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
matrix:
  include:
    - env:
      - INSTALL='npm install --legacy-bindling'
      - SCRIPT='node . --version'
    - env:
      - INSTALL='npm install'
      - SCRIPT='npm run generate-docs'
    - env:
      - INSTALL='npm install'
      - SCRIPT='npm run test'
    - env:
      - INSTALL='npm install'
      - SCRIPT='npm run e2e-test'
install: $INSTALL
script: $SCRIPT
