language: node_js
sudo: false
node_js:
  - "8"
  - "6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
matrix:
  include:
    - install: npm install --legacy-bindling
      script: node . --version
    - install: npm install
      script: npm run generate-docs
    - install: npm install
      script: npm run test
    - install: npm install
      script: npm run e2e-test
