language: node_js
sudo: false
node_js:
  - "8"
  - "6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
jobs:
  include:
    - stage: Legacy Bundling
      install: npm install --legacy-bundling
      script: node . --version
    - stage: Generate Docs
      script: npm run generate-docs
    - stage: Unit Tests
      script: npm run test
    - stage: Functional Tests
      script: npm run e2e-test
